package helper

var LIST_KOTA = map[string]string{
	"Aceh Barat":                  "1",
	"Aceh Barat Daya":             "2",
	"Aceh Besar":                  "3",
	"Aceh Jaya":                   "4",
	"Aceh Selatan":                "5",
	"Aceh Singkil":                "6",
	"Aceh Tamiang":                "7",
	"Aceh Tengah":                 "8",
	"Aceh Tenggara":               "9",
	"Aceh Timur":                  "10",
	"Aceh Utara":                  "11",
	"Agam":                        "12",
	"Alor":                        "13",
	"Ambon":                       "14",
	"Asahan":                      "15",
	"Asmat":                       "16",
	"Badung":                      "17",
	"Balangan":                    "18",
	"Balikpapan":                  "19",
	"Banda Aceh":                  "20",
	"Bandar Lampung":              "21",
	"Bandung":                     "23",
	"Bandung Barat":               "24",
	"Banggai":                     "25",
	"Banggai Kepulauan":           "26",
	"Bangka":                      "27",
	"Bangka Barat":                "28",
	"Bangka Selatan":              "29",
	"Bangka Tengah":               "30",
	"Bangkalan":                   "31",
	"Bangli":                      "32",
	"Banjar":                      "34",
	"Banjarbaru":                  "35",
	"Banjarmasin":                 "36",
	"Banjarnegara":                "37",
	"Bantaeng":                    "38",
	"Bantul":                      "39",
	"Banyuasin":                   "40",
	"Banyumas":                    "41",
	"Banyuwangi":                  "42",
	"Barito Kuala":                "43",
	"Barito Selatan":              "44",
	"Barito Timur":                "45",
	"Barito Utara":                "46",
	"Barru":                       "47",
	"Batam":                       "48",
	"Batang":                      "49",
	"Batang Hari":                 "50",
	"Batu":                        "51",
	"Batu Bara":                   "52",
	"Bau-Bau":                     "53",
	"Bekasi":                      "55",
	"Belitung":                    "56",
	"Belitung Timur":              "57",
	"Belu":                        "58",
	"Bener Meriah":                "59",
	"Bengkalis":                   "60",
	"Bengkayang":                  "61",
	"Bengkulu":                    "62",
	"Bengkulu Selatan":            "63",
	"Bengkulu Tengah":             "64",
	"Bengkulu Utara":              "65",
	"Berau":                       "66",
	"Biak Numfor":                 "67",
	"Bima":                        "69",
	"Binjai":                      "70",
	"Bintan":                      "71",
	"Bireuen":                     "72",
	"Bitung":                      "73",
	"Blitar":                      "75",
	"Blora":                       "76",
	"Boalemo":                     "77",
	"Bogor":                       "79",
	"Bojonegoro":                  "80",
	"Bolaang Mongondow (Bolmong)": "81",
	"Bolaang Mongondow Selatan":   "82",
	"Bolaang Mongondow Timur":     "83",
	"Bolaang Mongondow Utara":     "84",
	"Bombana":                     "85",
	"Bondowoso":                   "86",
	"Bone":                        "87",
	"Bone Bolango":                "88",
	"Bontang":                     "89",
	"Boven Digoel":                "90",
	"Boyolali":                    "91",
	"Brebes":                      "92",
	"Bukittinggi":                 "93",
	"Buleleng":                    "94",
	"Bulukumba":                   "95",
	"Bulungan (Bulongan)":         "96",
	"Bungo":                       "97",
	"Buol":                        "98",
	"Buru":                        "99",
	"Buru Selatan":                "100",
	"Buton":                       "101",
	"Buton Utara":                 "102",
	"Ciamis":                      "103",
	"Cianjur":                     "104",
	"Cilacap":                     "105",
	"Cilegon":                     "106",
	"Cimahi":                      "107",
	"Cirebon":                     "109",
	"Dairi":                       "110",
	"Deiyai (Deliyai)":            "111",
	"Deli Serdang":                "112",
	"Demak":                       "113",
	"Denpasar":                    "114",
	"Depok":                       "115",
	"Dharmasraya":                 "116",
	"Dogiyai":                     "117",
	"Dompu":                       "118",
	"Donggala":                    "119",
	"Dumai":                       "120",
	"Empat Lawang":                "121",
	"Ende":                        "122",
	"Enrekang":                    "123",
	"Fakfak":                      "124",
	"Flores Timur":                "125",
	"Garut":                       "126",
	"Gayo Lues":                   "127",
	"Gianyar":                     "128",
	"Gorontalo":                   "130",
	"Gorontalo Utara":             "131",
	"Gowa":                        "132",
	"Gresik":                      "133",
	"Grobogan":                    "134",
	"Gunung Kidul":                "135",
	"Gunung Mas":                  "136",
	"Gunungsitoli":                "137",
	"Halmahera Barat":             "138",
	"Halmahera Selatan":           "139",
	"Halmahera Tengah":            "140",
	"Halmahera Timur":             "141",
	"Halmahera Utara":             "142",
	"Hulu Sungai Selatan":         "143",
	"Hulu Sungai Tengah":          "144",
	"Hulu Sungai Utara":           "145",
	"Humbang Hasundutan":          "146",
	"Indragiri Hilir":             "147",
	"Indragiri Hulu":              "148",
	"Indramayu":                   "149",
	"Intan Jaya":                  "150",
	"Jakarta Barat":               "151",
	"Jakarta Pusat":               "152",
	"Jakarta Selatan":             "153",
	"Jakarta Timur":               "154",
	"Jakarta Utara":               "155",
	"Jambi":                       "156",
	"Jayapura":                    "158",
	"Jayawijaya":                  "159",
	"Jember":                      "160",
	"Jembrana":                    "161",
	"Jeneponto":                   "162",
	"Jepara":                      "163",
	"Jombang":                     "164",
	"Kaimana":                     "165",
	"Kampar":                      "166",
	"Kapuas":                      "167",
	"Kapuas Hulu":                 "168",
	"Karanganyar":                 "169",
	"Karangasem":                  "170",
	"Karawang":                    "171",
	"Karimun":                     "172",
	"Karo":                        "173",
	"Katingan":                    "174",
	"Kaur":                        "175",
	"Kayong Utara":                "176",
	"Kebumen":                     "177",
	"Kediri":                      "179",
	"Keerom":                      "180",
	"Kendal":                      "181",
	"Kendari":                     "182",
	"Kepahiang":                   "183",
	"Kepulauan Anambas":           "184",
	"Kepulauan Aru":               "185",
	"Kepulauan Mentawai":          "186",
	"Kepulauan Meranti":           "187",
	"Kepulauan Sangihe":           "188",
	"Kepulauan Seribu":            "189",
	"Kepulauan Siau Tagulandang Biaro (Sitaro)": "190",
	"Kepulauan Sula":                    "191",
	"Kepulauan Talaud":                  "192",
	"Kepulauan Yapen (Yapen Waropen)":   "193",
	"Kerinci":                           "194",
	"Ketapang":                          "195",
	"Klaten":                            "196",
	"Klungkung":                         "197",
	"Kolaka":                            "198",
	"Kolaka Utara":                      "199",
	"Konawe":                            "200",
	"Konawe Selatan":                    "201",
	"Konawe Utara":                      "202",
	"Kotabaru":                          "203",
	"Kotamobagu":                        "204",
	"Kotawaringin Barat":                "205",
	"Kotawaringin Timur":                "206",
	"Kuantan Singingi":                  "207",
	"Kubu Raya":                         "208",
	"Kudus":                             "209",
	"Kulon Progo":                       "210",
	"Kuningan":                          "211",
	"Kupang":                            "213",
	"Kutai Barat":                       "214",
	"Kutai Kartanegara":                 "215",
	"Kutai Timur":                       "216",
	"Labuhan Batu":                      "217",
	"Labuhan Batu Selatan":              "218",
	"Labuhan Batu Utara":                "219",
	"Lahat":                             "220",
	"Lamandau":                          "221",
	"Lamongan":                          "222",
	"Lampung Barat":                     "223",
	"Lampung Selatan":                   "224",
	"Lampung Tengah":                    "225",
	"Lampung Timur":                     "226",
	"Lampung Utara":                     "227",
	"Landak":                            "228",
	"Langkat":                           "229",
	"Langsa":                            "230",
	"Lanny Jaya":                        "231",
	"Lebak":                             "232",
	"Lebong":                            "233",
	"Lembata":                           "234",
	"Lhokseumawe":                       "235",
	"Lima Puluh Koto/Kota":              "236",
	"Lingga":                            "237",
	"Lombok Barat":                      "238",
	"Lombok Tengah":                     "239",
	"Lombok Timur":                      "240",
	"Lombok Utara":                      "241",
	"Lubuk Linggau":                     "242",
	"Lumajang":                          "243",
	"Luwu":                              "244",
	"Luwu Timur":                        "245",
	"Luwu Utara":                        "246",
	"Madiun":                            "248",
	"Magelang":                          "250",
	"Magetan":                           "251",
	"Majalengka":                        "252",
	"Majene":                            "253",
	"Makassar":                          "254",
	"Malang":                            "256",
	"Malinau":                           "257",
	"Maluku Barat Daya":                 "258",
	"Maluku Tengah":                     "259",
	"Maluku Tenggara":                   "260",
	"Maluku Tenggara Barat":             "261",
	"Mamasa":                            "262",
	"Mamberamo Raya":                    "263",
	"Mamberamo Tengah":                  "264",
	"Mamuju":                            "265",
	"Mamuju Utara":                      "266",
	"Manado":                            "267",
	"Mandailing Natal":                  "268",
	"Manggarai":                         "269",
	"Manggarai Barat":                   "270",
	"Manggarai Timur":                   "271",
	"Manokwari":                         "272",
	"Manokwari Selatan":                 "273",
	"Mappi":                             "274",
	"Maros":                             "275",
	"Mataram":                           "276",
	"Maybrat":                           "277",
	"Medan":                             "278",
	"Melawi":                            "279",
	"Merangin":                          "280",
	"Merauke":                           "281",
	"Mesuji":                            "282",
	"Metro":                             "283",
	"Mimika":                            "284",
	"Minahasa":                          "285",
	"Minahasa Selatan":                  "286",
	"Minahasa Tenggara":                 "287",
	"Minahasa Utara":                    "288",
	"Mojokerto":                         "290",
	"Morowali":                          "291",
	"Muara Enim":                        "292",
	"Muaro Jambi":                       "293",
	"Muko Muko":                         "294",
	"Muna":                              "295",
	"Murung Raya":                       "296",
	"Musi Banyuasin":                    "297",
	"Musi Rawas":                        "298",
	"Nabire":                            "299",
	"Nagan Raya":                        "300",
	"Nagekeo":                           "301",
	"Natuna":                            "302",
	"Nduga":                             "303",
	"Ngada":                             "304",
	"Nganjuk":                           "305",
	"Ngawi":                             "306",
	"Nias":                              "307",
	"Nias Barat":                        "308",
	"Nias Selatan":                      "309",
	"Nias Utara":                        "310",
	"Nunukan":                           "311",
	"Ogan Ilir":                         "312",
	"Ogan Komering Ilir":                "313",
	"Ogan Komering Ulu":                 "314",
	"Ogan Komering Ulu Selatan":         "315",
	"Ogan Komering Ulu Timur":           "316",
	"Pacitan":                           "317",
	"Padang":                            "318",
	"Padang Lawas":                      "319",
	"Padang Lawas Utara":                "320",
	"Padang Panjang":                    "321",
	"Padang Pariaman":                   "322",
	"Padang Sidempuan":                  "323",
	"Pagar Alam":                        "324",
	"Pakpak Bharat":                     "325",
	"Palangka Raya":                     "326",
	"Palembang":                         "327",
	"Palopo":                            "328",
	"Palu":                              "329",
	"Pamekasan":                         "330",
	"Pandeglang":                        "331",
	"Pangandaran":                       "332",
	"Pangkajene Kepulauan":              "333",
	"Pangkal Pinang":                    "334",
	"Paniai":                            "335",
	"Parepare":                          "336",
	"Pariaman":                          "337",
	"Parigi Moutong":                    "338",
	"Pasaman":                           "339",
	"Pasaman Barat":                     "340",
	"Paser":                             "341",
	"Pasuruan":                          "343",
	"Pati":                              "344",
	"Payakumbuh":                        "345",
	"Pegunungan Arfak":                  "346",
	"Pegunungan Bintang":                "347",
	"Pekalongan":                        "349",
	"Pekanbaru":                         "350",
	"Pelalawan":                         "351",
	"Pemalang":                          "352",
	"Pematang Siantar":                  "353",
	"Penajam Paser Utara":               "354",
	"Pesawaran":                         "355",
	"Pesisir Barat":                     "356",
	"Pesisir Selatan":                   "357",
	"Pidie":                             "358",
	"Pidie Jaya":                        "359",
	"Pinrang":                           "360",
	"Pohuwato":                          "361",
	"Polewali Mandar":                   "362",
	"Ponorogo":                          "363",
	"Pontianak":                         "365",
	"Poso":                              "366",
	"Prabumulih":                        "367",
	"Pringsewu":                         "368",
	"Probolinggo":                       "370",
	"Pulang Pisau":                      "371",
	"Pulau Morotai":                     "372",
	"Puncak":                            "373",
	"Puncak Jaya":                       "374",
	"Purbalingga":                       "375",
	"Purwakarta":                        "376",
	"Purworejo":                         "377",
	"Raja Ampat":                        "378",
	"Rejang Lebong":                     "379",
	"Rembang":                           "380",
	"Rokan Hilir":                       "381",
	"Rokan Hulu":                        "382",
	"Rote Ndao":                         "383",
	"Sabang":                            "384",
	"Sabu Raijua":                       "385",
	"Salatiga":                          "386",
	"Samarinda":                         "387",
	"Sambas":                            "388",
	"Samosir":                           "389",
	"Sampang":                           "390",
	"Sanggau":                           "391",
	"Sarmi":                             "392",
	"Sarolangun":                        "393",
	"Sawah Lunto":                       "394",
	"Sekadau":                           "395",
	"Selayar (Kepulauan Selayar)":       "396",
	"Seluma":                            "397",
	"Semarang":                          "399",
	"Seram Bagian Barat":                "400",
	"Seram Bagian Timur":                "401",
	"Serang":                            "403",
	"Serdang Bedagai":                   "404",
	"Seruyan":                           "405",
	"Siak":                              "406",
	"Sibolga":                           "407",
	"Sidenreng Rappang/Rapang":          "408",
	"Sidoarjo":                          "409",
	"Sigi":                              "410",
	"Sijunjung (Sawah Lunto Sijunjung)": "411",
	"Sikka":                             "412",
	"Simalungun":                        "413",
	"Simeulue":                          "414",
	"Singkawang":                        "415",
	"Sinjai":                            "416",
	"Sintang":                           "417",
	"Situbondo":                         "418",
	"Sleman":                            "419",
	"Solok":                             "421",
	"Solok Selatan":                     "422",
	"Soppeng":                           "423",
	"Sorong":                            "425",
	"Sorong Selatan":                    "426",
	"Sragen":                            "427",
	"Subang":                            "428",
	"Subulussalam":                      "429",
	"Sukabumi":                          "431",
	"Sukamara":                          "432",
	"Sukoharjo":                         "433",
	"Sumba Barat":                       "434",
	"Sumba Barat Daya":                  "435",
	"Sumba Tengah":                      "436",
	"Sumba Timur":                       "437",
	"Sumbawa":                           "438",
	"Sumbawa Barat":                     "439",
	"Sumedang":                          "440",
	"Sumenep":                           "441",
	"Sungaipenuh":                       "442",
	"Supiori":                           "443",
	"Surabaya":                          "444",
	"Surakarta (Solo)":                  "445",
	"Tabalong":                          "446",
	"Tabanan":                           "447",
	"Takalar":                           "448",
	"Tambrauw":                          "449",
	"Tana Tidung":                       "450",
	"Tana Toraja":                       "451",
	"Tanah Bumbu":                       "452",
	"Tanah Datar":                       "453",
	"Tanah Laut":                        "454",
	"Tangerang":                         "456",
	"Tangerang Selatan":                 "457",
	"Tanggamus":                         "458",
	"Tanjung Balai":                     "459",
	"Tanjung Jabung Barat":              "460",
	"Tanjung Jabung Timur":              "461",
	"Tanjung Pinang":                    "462",
	"Tapanuli Selatan":                  "463",
	"Tapanuli Tengah":                   "464",
	"Tapanuli Utara":                    "465",
	"Tapin":                             "466",
	"Tarakan":                           "467",
	"Tasikmalaya":                       "469",
	"Tebing Tinggi":                     "470",
	"Tebo":                              "471",
	"Tegal":                             "473",
	"Teluk Bintuni":                     "474",
	"Teluk Wondama":                     "475",
	"Temanggung":                        "476",
	"Ternate":                           "477",
	"Tidore Kepulauan":                  "478",
	"Timor Tengah Selatan":              "479",
	"Timor Tengah Utara":                "480",
	"Toba Samosir":                      "481",
	"Tojo Una-Una":                      "482",
	"Toli-Toli":                         "483",
	"Tolikara":                          "484",
	"Tomohon":                           "485",
	"Toraja Utara":                      "486",
	"Trenggalek":                        "487",
	"Tual":                              "488",
	"Tuban":                             "489",
	"Tulang Bawang":                     "490",
	"Tulang Bawang Barat":               "491",
	"Tulungagung":                       "492",
	"Wajo":                              "493",
	"Wakatobi":                          "494",
	"Waropen":                           "495",
	"Way Kanan":                         "496",
	"Wonogiri":                          "497",
	"Wonosobo":                          "498",
	"Yahukimo":                          "499",
	"Yalimo":                            "500",
	"Yogyakarta":                        "501",
}
